### PR TITLE
Safety improvements: mitigation for PR #390

### PR DESCRIPTION
**Pull request by neysofu**
This is a follow-up PR to https://github.com/spacemeshos/svm/pull/411.

https://github.com/spacemeshos/svm/pull/390 fixed a Fixed-Gas regression in `svm-abi-decoder`, meaning that some code had been merged into `master` which caused the compiled `.wasm` artifacts to contain illegal `loop` instructions. This broke SVM Fixed-Gas mode, so we reverted back to using pointers within `Cursor`.

This PR mitigates the two issues:
- It doesn't compile into any `loop` instructions and invalid WASM code.
- It reverts *some* of the safety improvements applied before breaking Fixed-Gas. In particular, we introduce back explicit lifetimes, which help the compiler check for some useful invariants and reduces the UB surface.

### CODE REVIEW

**Review by kobby-pentangeli — CHANGES_REQUESTED** [review]
Two runtime tests are failing. Kindly review the following:

Running tests\runtime_tests.rs (target\debug\deps\runtime_tests-a11e206cb6fa353e.exe)

running 15 tests
...

test `memory_runtime_call_success` ... FAILED
test `memory_runtime_call_func_not_found` ... FAILED

failures:

---- memory_runtime_call_success stdout ----
thread 'memory_runtime_call_success' panicked at 'assertion failed: receipt.success', 
crates\runtime\tests\runtime_tests.rs:339:5

---- memory_runtime_call_func_not_found stdout ----
thread 'memory_runtime_call_func_not_found' panicked at 'assertion failed: receipt.success', crates\runtime\tests\runtime_tests.rs:293:5

**Comment by neysofu** [comment]
@kobby-pentangeli Can you please provide more details? How does your setup differ from the CI's, where these two tests indeed succeed?

**Comment by kobby-pentangeli** [comment]
@neysofu All tests pass when I run this branch inside of my **WSL-Ubuntu-20.4-LTS** (running on Windows 11). However, the two tests I referenced above fail on native Windows 11.

**Review by kobby-pentangeli — APPROVED** [review]

**Comment by neysofu** [comment]
Ok, let's make a note to investigate this in the future.

**Pull request merged**
